# Generated by Django 5.0.7 on 2024-07-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_assistants"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="al_syera",
            field=models.CharField(default=0.7718237346324691, max_length=50),
        ),
    ]
