# Generated by Django 5.0.7 on 2024-07-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_student_al_syera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="al_syera",
            field=models.CharField(max_length=50),
        ),
    ]
